// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./src/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/ui/dialog/DialogHeader.vue')['default']
    DialogScrollContent: typeof import('./src/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./src/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./src/components/ui/dialog/DialogTrigger.vue')['default']
    Help: typeof import('./src/components/Help.vue')['default']
    Markmap: typeof import('./src/components/Markmap.vue')['default']
    Pen: typeof import('./src/components/Pen.vue')['default']
  }
}
